# -*- coding: utf-8 -*-
"""Counting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zx6jKbnh0GZqAY3pKLNz3NAYJRwe-lBb
"""

scores = input().split()
count = 0
for i in scores:
    if int(i) < 60:
        count = count + 1

print(count)